osx_image: xcode9.3
language: objective-c
xcode_workspace: calendar99.xcworkspace
xcode_scheme: calendar99-logic
xcode_sdk: iphonesimulator11.2

branches:
  except:
  - selectionHighlight

before_install:
- gem install cocoapods slather xcpretty
- pod repo update

script:
- set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace calendar99.xcworkspace -scheme calendar99-logic -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty

after_success: slather